name: Python quality

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  check_quality:
    name: Quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        python-version: ['3.8', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: pip install tox

    - name: Check Quality
      run: tox -e quality
