name: Python tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        python-version: ['3.8', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: setup firefox
      uses: browser-actions/setup-firefox@v1

    - name: Install dependencies
      run: pip install tox

    - name: Run tests
      run: tox -e py38-django32
